require("braint.cmp")
require("braint.options")
require("braint.plugins")
require("braint.icons")
require("braint.colorscheme")
require("braint.lsp")
require("braint.nvim-tree")
require("braint.autopairs")
require("braint.lualine")
require("braint.lir")
require("braint.telescope")
require("braint.keymaps")
require("braint.comment")
require("braint.lsp-inlayhints")
-- require("braint.winbar")
